@DataGridServer_HostAddress = http://localhost:5123

GET {{DataGridServer_HostAddress}}/api/Values/SeedData
Accept: application/json

###

GET {{DataGridServer_HostAddress}}/api/Values/GetAll?skip=5&top=10

###
